apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-example-deployment
  labels:
    app: gitops-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-example
  template:
    metadata:
      labels:
        app: gitops-example
    spec:
      containers:
      - name: hello-world
        image: migsking/hello-world:latest
        ports:
        - containerPort: 8080